name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build & Upload Release Binaries
    uses: ./.github/workflows/build-app.yml
    with:
      upload-release: true
    secrets: inherit
